# fly.toml app configuration file generated for fullstack-client on 2023-08-21T21:35:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fullstack-client"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 5173
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
