name: Run Jest Tests on PR

on:
  pull_request:
    branches:
      - main  # Update this to your main branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 19.7.0

      - name: Install Dependencies
        run: npm install

      - name: Run Jest Tests
        run: npm test
